# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=native"]

# [target.x86_64-unknown-linux-musl]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=native"]

# [build]
# rustflags = ["-C", "target-cpu=native"] # -Z threads requires nightly

# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
